# Generated by Django 5.2.3 on 2025-06-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='svg_icono',
            field=models.TextField(default='', help_text='Pega aquí el código SVG del icono'),
            preserve_default=False,
        ),
    ]
