# Generated by Django 5.2.3 on 2025-06-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_materia_svg_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='id_coorte',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_materia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='core.materia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrera',
            name='svg_icono',
            field=models.TextField(default='', help_text='Pega aquí el código SVG del icono'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Corte',
        ),
    ]
