# Generated by Django 5.2.3 on 2025-06-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_asignatura_id_coorte_asignatura_id_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
    ]
