# Generated by Django 5.2.3 on 2025-06-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_alumno_cedula_alter_profesor_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='titulo',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='tema_general',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
