# Generated by Django 5.2.3 on 2025-06-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_asignatura_titulo_asignatura_tema_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='tipo_evaluacion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
