# Generated by Django 5.2.3 on 2025-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_asignatura_tipo_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
