# Generated by Django 5.2.3 on 2025-06-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profesor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='tipo_evaluacion',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
