# Generated by Django 5.2.3 on 2025-07-01 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_asignatura_tipo_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='id_profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_asignadas', to='core.profesor'),
        ),
    ]
